// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkiLj_t94-19vwZETF4_-Q2qeb9AOE00Y',
    appId: '1:94983728430:web:e703faffc5437416de9ebf',
    messagingSenderId: '94983728430',
    projectId: 'gym-tracker-72897',
    authDomain: 'gym-tracker-72897.firebaseapp.com',
    storageBucket: 'gym-tracker-72897.appspot.com',
    measurementId: 'G-DYLZDN7FG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKlhIjX_zdXrpl638kVkyzBAnzLtvFa1g',
    appId: '1:94983728430:android:b3df824c579967cade9ebf',
    messagingSenderId: '94983728430',
    projectId: 'gym-tracker-72897',
    storageBucket: 'gym-tracker-72897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHHRNKM8K5PnZH0sGhgg9HbL9rKEE3-bo',
    appId: '1:94983728430:ios:e40273ab93af649cde9ebf',
    messagingSenderId: '94983728430',
    projectId: 'gym-tracker-72897',
    storageBucket: 'gym-tracker-72897.appspot.com',
    iosClientId: '94983728430-7fbf46brl0a3s5olt94u8nvu1bnffndu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHHRNKM8K5PnZH0sGhgg9HbL9rKEE3-bo',
    appId: '1:94983728430:ios:f37e608416c5a3b6de9ebf',
    messagingSenderId: '94983728430',
    projectId: 'gym-tracker-72897',
    storageBucket: 'gym-tracker-72897.appspot.com',
    iosClientId: '94983728430-rsqq1bcfohbafq42p0cu8kn835phkj2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymTracker.RunnerTests',
  );
}
