name: gym_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.14.0
  cached_network_image: ^3.3.1
  firebase_storage: ^11.6.0
  easy_date_timeline: ^1.0.4
  day_night_time_picker: ^1.3.0+1
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  image_cropper: ^5.0.1
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/